- hosts: all
  tasks:
  - name: Install apache 
    include: CentOS.yml
  - name: Install packages
    include: packages.yml  
  - name: Install php
    include: php.yml
  - name: Install wordpress
    include: wordpress.yml
  - name: Install mariadb
    include: db.yml